global:
  scrape_interval: 15s  # Check metrics every 15 seconds
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'messenger-backend'
    static_configs:
      - targets: ['backend:5000'] 
    metrics_path: '/metrics'  